#!/bin/bash

#      2 Did not receive identification string from 76.74.252.60
#      2 Invalid user deploy from 211.143.157.130

if [ "${1}" = "" ]
then
	logfile="/var/log/auth.log"
else
	logfile="$*"
fi

# ---

(
ufw status \
| gawk '
    $2 == "DENY" \
    {
	printf "UFW %s\n", $3;
    }'

gawk '\
    /sshd/ && / Did not receive identification string from / \
    {
	printf "N/A %s\n", $NF
    }

    /sshd/ && / Invalid user [a-zA-Z0-9_-]* from / \
    {
	sub( "^.* Invalid user ", "");
	sub( " from ", " ");
	print;
    }

    /sshd/ && /Failed password/ \
    {
	sub( "^.*Failed password for ", "");
	sub( "^invalid user ", "");
	sub( " port .*$", "");
	sub( " from ", " ");
	print;
    }' ${logfile} \
| gawk '
    {
	freq[ $2]++;
    }

    END \
    {
	for( ip in freq)
	{
	    printf "FAIL %s %d\n", ip, freq[ ip];
	}
    }'
) | gawk '

    $1 == "UFW" \
    {
	blocked[ $2] = 1;
    }

    $1 == "FAIL" \
    {
	failed[ $2] = $3;
#printf "dbg:: Failed %s %d\n", $2, failed[ $2];
    }

    END \
    {
	for( ip in failed)
	{
	    if( blocked[ ip]) printf "Blocked %s\n", ip;
	    else printf "New %s %d\n", ip, failed[ ip];
	}
    }'
