#!/usr/bin/env python
"""
Display data added to the indicated log file since the previous invocation.
"""

import pickle
import sys
import os
import pwd

# ---

SHOW_SYNTAX = "Syntax: {comm} log-file-name"

CKPT_TEMPLATE = "/var/tmp/{who}-{inp}.CKPT"

NAME = "input"
FPOS = "fpos"

DONE = False

ABS_POS = 0
FROM_START = 1
FROM_END = 2

# ---

if len(sys.argv) > 1:
    LOG_FILE = sys.argv[1]
    BASE = LOG_FILE.split("/")[-1]

    USERNAME = pwd.getpwuid(os.getuid()).pw_name

    CKPT_FILE = CKPT_TEMPLATE.format(inp=BASE, who=USERNAME)


else:
    print SHOW_SYNTAX.format(comm=sys.argv[0])
    DONE = True

# ---

if not DONE:
    try:
        CKPT = open(CKPT_FILE, "rb+")
        LOGINFO = pickle.load(CKPT)
        CKPT.close()

    except IOError:
        LOGINFO = dict()
        LOGINFO[NAME] = LOG_FILE
        LOGINFO[FPOS] = 0

# ---

if not DONE:
    START = LOGINFO[FPOS]

    LOG = open(LOGINFO[NAME], "rb")

    LOG.seek(0, FROM_END)
    FSIZE = LOG.tell()

    if FSIZE >= START:
        LOG.seek(START, ABS_POS)
    else:
        LOG.seek(0, ABS_POS)
        START = 0

    NEWDATA = LOG.read()

    LOGINFO[FPOS] = LAST = LOG.tell()

    if LAST > START:
        sys.stdout.write(NEWDATA)

    CKPT = open(CKPT_FILE, "wb+")
    pickle.dump(LOGINFO, CKPT)

